Algoritmo "segundos dia"

//Faça um programa em Português Estruturado que solicite a hora atual (expressa em horas,
//minutos e segundos) ao usuário e informe quantos segundos do dia já passaram.

Var

h, m, SegDia: inteiro

Inicio

escreval("Primeiro me diz a hora:")
leia(H)

escreval("Agora me diz o minuto:")
leia(M)

SegDia <- h * m * 60

escreval("Ja se passaram ", SegDia, " segundos.")
Fimalgoritmo